project: 
  type: website
  output-dir: docs
  render:
    - "*.*"
    - "!tutorials/r/gdalcubes.qmd"
    - "!tutorials/r/5-r-geospatial.qmd"

execute:
  freeze: auto
  
website:
  page-navigation: true  
  title: "2025 EDMW Workshop - PACE"
  favicon: "images/favicon-16x16.png"
  site-url: https://nmfs-opensci.github.io/EDMW-EarthData-Workshop-2025
  repo-url: https://github.com/nmfs-opensci/EDMW-EarthData-Workshop-2025
  repo-actions: [edit, issue, source]
  
  page-footer: <img src="https://github.com/nmfs-opensci/assets/blob/main/logo/nmfs-opensci-logo2.png?raw=true" alt="NMFS Open Science logo" style="width:150px"><br />NMFS Open Science (2025)
 
  sidebar:
    logo: https://github.com/nmfs-opensci/assets/blob/main/logo/nmfs-opensci-logo2.png?raw=true
    pinned: true
    align: center
    
    style: "docked"
    collapse-level: 1
    toc-expand: false
    contents:
      - section: "Welcome"
        href: index.md
        contents:
          - team.md
          - schedule.md
          - setup.qmd
          - section: Orientation
            contents:
            - text: RStudio
              href: content/02-rstudio.qmd
            - text: Earthdata login
              href: content/02-earthdata.md
            - text: Local set-up - R
              href: content/02-local-setup-r.qmd
            - text: Local set-up - Python
              href: content/02-local-setup-python.qmd
            - text: Git-Authentication
              href: content/02-git.md
            - text: Git-JupyterLab
              href: content/02-git-jupyter.md
            - text: Git-RStudio
              href: content/02-git-rstudio.md
          - coc.md
      - section: "Lectures"
        href: lectures/index.md
        contents:
          - lectures/Intro-to-PACE.pdf
          - lectures/PACE-Products.pdf
      - section: "Tutorials"
        contents:
          - section: "Welcome"
            contents:
              - text: Welcome
                href: content/01-welcome.md
              - text: Geoscience cloud tools
                href: content/01-intro-to-cloud.qmd
              - text: Jupyter hubs
                href: content/01-intro-to-jupyterhub.md
          - section: "Tutorials"
            contents:
              - text: ED Catalog
                href: tutorials/python/0-earthdata-catalog.ipynb
              - text: Search
                href: tutorials/python/1-earthaccess.ipynb
              - text: Rrs and AVW
                href: tutorials/python/Tutorial_2_Rrs_AVW.ipynb
              - text: MOANA
                href: tutorials/python/Tutorial_3_moana-erddap.ipynb
              - text: Kd
                href: tutorials/python/Tutorial_4_kd.ipynb
      - text: <img width=100px>
      - text: <img src="/images/noaa_emblem_logo-2022.png" width=100px>
        href: https://fisheries.noaa.gov
  navbar:
    background: primary
    search: true
    right: 
      - icon: server
        href: https://workshop.nmfs-openscapes.2i2c.cloud/
        text: "JupyterHub"
      - icon: github
        href: https://github.com/nmfs-opensci/EDMW-EarthData-Workshop-2025
        text: "Repo"
      - icon: globe
        href: https://github.com/nmfs-opensci
        text: "GH org"


format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true
    toc-depth: 2
    include-before-body: translate.html

filters:
  - include-files.lua
  - quarto
