project: 
  type: website
  output-dir: docs
  render:
    - "*.*"
    - "!tutorials/Tutorial_3_moana-erddap-clean.ipynb"
    
default-image-extension: ""

resources:
  - tutorials/*.csv
  - tutorials/interactive_kd.html
  - tutorials/Tutorial_3_moana-erddap-clean.ipynb
  - lectures/*.pdf
  - widgets/jupyterhub_link_widget.html
  - widgets/widget-popout.html

execute:
  freeze: auto
  
website:
  page-navigation: true  
  title: "2025 EDMW Workshop - PACE"
  favicon: "images/favicon-16x16.png"
  site-url: https://nmfs-opensci.github.io/EDMW-EarthData-Workshop-2025
  repo-url: https://github.com/nmfs-opensci/EDMW-EarthData-Workshop-2025
  repo-actions: [edit, issue, source]
  
  page-footer: <img src="https://github.com/nmfs-opensci/assets/blob/main/logo/nmfs-opensci-logo2.png?raw=true" alt="NMFS Open Science logo" style="width:150px"><br />NMFS Open Science (2025)
 
  sidebar:
    logo: https://github.com/nmfs-opensci/assets/blob/main/logo/nmfs-opensci-logo2.png?raw=true
    pinned: true
    align: center
    
    style: "docked"
    collapse-level: 1
    toc-expand: false
    contents:
      - section: "Welcome"
        href: index.qmd
        contents:
          - content/schedule.md
          - content/setup.md
          - content/team.md
          - text: Why cloud(-native) data?
            href: content/why-cloud.qmd
          - text: Jupyter Hub and Lab
            href: content/jupyterhub.md
      - section: "Lectures"
        href: lectures/index.md
        contents:
          - text: Intro to Hyperspectral
            href: lectures/Intro-to-hyperspectral.pdf
          - text: PACE Products
            href: lectures/PACE-Products.pdf
      - section: "Tutorials"
        contents:
          - text: Search
            href: tutorials/Tutorial_0_search.ipynb
          - text: Data Access
            href: tutorials/Tutorial_1_access.ipynb
          - text: Rrs and AVW
            href: tutorials/Tutorial_2_Rrs_AVW.ipynb
          - text: Kd
            href: tutorials/Tutorial_4_kd.ipynb
          - text: MOANA
            href: tutorials/Tutorial_3_moana-erddap.ipynb
      - content/resources.md
      - coc.md
      - text: <img width=100px>
      - text: <img src="/images/noaa_emblem_logo-2022.png" width=100px>
        href: https://fisheries.noaa.gov
  navbar:
    background: primary
    search: true
    right: 
      - icon: server
        href: https://workshop.nmfs-openscapes.2i2c.cloud/
        text: "JupyterHub"
      - icon: github
        href: https://github.com/nmfs-opensci/EDMW-EarthData-Workshop-2025
        text: "Repo"
      - icon: globe
        href: https://github.com/nmfs-opensci
        text: "GH org"


format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true
    toc-depth: 2
    include-before-body:
      - translate.html
      - widgets/widget-popout.html

#filters:
#  - include-files.lua
#  - quarto
